### ISSUE TITLE
Page home - W3C

### ISSUE THREAD

**Issue by Chloebert** [WildCodeSchool/2022-03-php-orleans-project-kevrenn#222]
Ne passe pas la validation "Error: Bad value /assets/images/↩																							portrait-placeholder.png for attribute src on element [img](https://html.spec.whatwg.org/multipage/#the-img-element): Tab, new line or carriage return found."

**Comment by VanTej** [comment]
tab nécessaires dans la condition boucle sinon ligne trop longue
